# Основное поле - указание версии. Зависит от возможностей которые мы используем
version: "3.5"

# Далее перечисляем сервисы, которые будут запущены нашим docker-compose файлом

services:
  # Сначала указываем имя сервиса (и по умолчанию также назовётся контейнер
  app:
#   Указываем имя образа который будем использовать. По этому имени мы НЕ получаем его
    image: django-app-docker-compose
#   В разделе build указываем откуда берём image
#   context . значтт что мы будем в текущем каталоге искать Dockerfile и запускать из него сборку dokcer image
    build:
      context: .
#   Чтобы подключиться нужно настроить проброс порта внутрь этого контейнера
#   Указываем порты 8000 на компе 8000 в контейнере
    ports:
      - "8000:8000"



